### ISSUE TITLE
Update opens new tab, pulling focus

### ISSUE THREAD

**Issue by GerritPlehn** [saucettv/VideoAdBlockForTwitch#7]
> Extension will now auto show options on first install/update.

I'd suggest that showing options on update should be removed or modified as well.
As it opens a new tab in the browser it pulls focus from whatever you might be doing in another full screen window (playing games?).
Maybe open the settings page if you're currently on twitch.tv or only show a pop-up notification, so that the user is not forcefully interrupted.

**Comment by LordMrcS** [comment]
I second this, just had my spreadsheet sent to background and the browser popped in with a donate now message.

**Comment by GerritPlehn** [comment]
After checking the version number in the Chrome webstore, I noticed that it is trailing two versions behind and this issue was fixed in 4.7. Looking forward to 4.8 :+1:

**Comment by saucettv** [comment]
Hi, yeah sorry, it was coded to simply show the extension options page to new users or users who have updated the extension. I had no idea Chrome pulls the focus away automatically, at a random time. The options page of the extension does have a donations link hence everyone thinking it's me spamming my donations link.

It was fixed in 4.8 as soon as I knew about it, Firefox is already updated, but Chrome takes days to review, so it's a struggle :(
